name: Release
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: deployment
  cancel-in-progress: false
jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: echo publish
